src/controllers/MenuController.php
<?php

namespace maerduq\usm\controllers;

use maerduq\usm\components\UsmController;
use maerduq\usm\components\Usm;
use maerduq\usm\models\MenuItem;
use maerduq\usm\models\Page;
use maerduq\usm\models\Redirect;
use maerduq\usm\UsmModule;
use Yii;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

class MenuController extends UsmController {

    public $options = [];

    public function behaviors() {
        $behaviors = parent::behaviors();
        $behaviors['verbs'] = [
            'class' => VerbFilter::class,
            'actions' => [
                'delete'  => ['post'],
                'ajax' => ['post']
            ],
        ];
        return $behaviors;
    }

    public function beforeAction($action) {
        if ($action->id === 'ajax') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionIndex($sudo = null) {
        $items = MenuItem::find()
            ->with(['redirect', 'page', 'children'])
            ->where(['parent_id' => null])
            ->orderBy(['position' => SORT_ASC])
            ->all();

        return $this->render('index', [
            'items' => $items,
            'sudo' => $sudo
        ]);
    }

    public function actionCreate($page = null, $return = null) {
        $model = new MenuItem();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', UsmModule::t('menu', 'Menu item has been created.'));
            return $this->redirect(Usm::returnUrl($return, ['update', 'id' => $model->id]));
        } elseif ($page != null) {
            $page = Page::findOne($page);
            if ($page !== null) {
                $model->visible = 1;
                $model->type = 'cms';
                $model->page_id = $page->id;
                $model->title = $page->title;
            }
        }

        $this->view->params['cms_options'] = $this->getOptions(Page::class, 'title', [], false);

        return $this->render('create', [
            'model' => $model,
            'return' => $return
        ]);
    }

    public function actionUpdate($id = null, $return = null) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', UsmModule::t('menu', 'Menu item has been edited.'));
            return $this->refresh();
        }

        $this->view->params['cms_options'] = $this->getOptions(Page::class, 'title', [], false);

        return $this->render('update', [
            'model' => $model,
            'return' => $return
        ]);
    }

    public function actionDelete($id = null) {
        $model = MenuItem::findOne($id);
        if ($model != null) {
            Redirect::deleteAll('menu_item_id = :id', ['id' => $id]);
            $model->delete();
            $sql = ($model->parent_id == null) ?
                "UPDATE " . MenuItem::tableName() . " SET position = position-1 WHERE parent_id IS NULL && position >= :order" :
                "UPDATE " . MenuItem::tableName() . " SET position = position-1 WHERE parent_id = :parent && position >= :order";
            $params = ($model->parent_id == null) ?
                ['order' => $model->position] :
                ['parent' => $model->parent_id, 'order' => $model->position];
            Yii::$app->db->createCommand($sql)->bindValues($params)->execute();
            Yii::$app->session->setFlash('success', UsmModule::t('menu', 'Menu item has been deleted.'));
        }
        $this->redirect(['index']);
        return;
    }


    public function actionAjax($action) {
        switch ($action) {
            case 'order':
                return $this->ajaxOrder();
                break;
            default:
                throw new NotFoundHttpException();
        }
    }

    public function ajaxOrder() {
        $newOrder = Yii::$app->request->post('newOrder');
        foreach ($newOrder as $op) {
            $item = MenuItem::findOne($op['id']);
            if ($item === null) {
                continue;
            }
            $item->parent_id = $op['parent_id'];
            $item->position = $op['position'];
            $item->save();
        }
        return 1;
    }

    /**
     * Finds the MenuItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MenuItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = MenuItem::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(UsmModule::t('error', 'The requested page does not exist.'));
    }
}

src/views/pages/_form.php
<?php

use yii\bootstrap5\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use maerduq\usm\components\Usm;
use maerduq\usm\UsmModule;

if (!isset($formConfig)) {
    $formConfig = [];
}

$form = ActiveForm::begin($formConfig);

if (!isset($withButtons)) {
    $withButtons = true;
}

$defaultReturnUrl = ['index'];
if (!isset($returnUrl)) {
    $returnUrl = $defaultReturnUrl;
}
?>

<?php foreach (Usm::getLanguages() as $lang) : ?>
    <?php if ($lang === Usm::getBaseLanguage()) : ?>
        <?= $form->field($model, 'title', [
            'template' => (count(Usm::getLanguages()) === 1) ? "{label}\n{input}\n{hint}\n{error}" :
                "{label}\n<div class='input-group'>
                <span class='input-group-text'>{$lang}</span>
                {input}
                </div>\n{hint}\n{error}"
        ]) ?>
    <?php else : ?>
        <div class="mb-3">
            <div class="input-group">
                <span class="input-group-text"><?= $lang ?></span>
                <input type="text" class="form-control" name="Page[translations][title][<?= $lang ?>]" value="<?= $model->getTranslation('title', $lang, false) ?>" />
            </div>
        </div>
    <?php endif ?>
<?php endforeach ?>

<?= $form->field($model, 'access')->radioList(Usm::getAccessOptions(), ['size' => 3])->hint(UsmModule::t('pages', 'Which users should be able to visit this page?')); ?>

<hr />

<?= $form->field($model, 'style')->dropDownList($model->styleOptions) ?>
<?= $form->field($model, 'rawEdit')->checkbox() ?>

<hr />
<div class="btn-toolbar">
    <?= Html::submitButton(UsmModule::t('usm', 'Save'), ['class' => 'btn btn-primary me-2']) ?>
    <?php if (!$model->isNewRecord) : ?>
        <?= Html::a(UsmModule::t('usm', 'Edit content'), ['interpret/page', 'id' => $model->id, 'usm' => ['editMode' => 1], 'returnUrl' => Url::current()], ['class' => 'btn btn-secondary me-2']) ?>
    <?php endif ?>
    <?php if ($withButtons) : ?>
        <?= Html::a(UsmModule::t('usm', 'Back'), $returnUrl, ['class' => 'btn btn-link']) ?>
    <?php endif ?>
</div>


<?php ActiveForm::end() ?>

src/views/pages/create.php
<?php

use maerduq\usm\UsmModule;

$this->title = UsmModule::t('pages', "Create new page");
$this->params['breadcrumbs'] = [
    ['label' => UsmModule::t('usm', 'Pages'), 'url' => ['index']],
    $this->title,
];

echo $this->render('_form', ['model' => $model, 'return' => $return]);

src/views/pages/index.php
<?php

/* @var $this yii\web\View */
/* @var $searchModel app\models\PageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

use maerduq\usm\components\Usm;
use maerduq\usm\UsmModule;
use maerduq\usm\widgets\IconWidget;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

$this->title = UsmModule::t('usm', "Pages");

?>

<?php $this->beginBlock('intro'); ?>
<p>
    <?= UsmModule::t('pages', 'Here you can manage the editable pages - so called USM pages - of your website. You can edit the pages as if you are editing a Word document.') ?>
    <?= Html::a(UsmModule::t('pages', 'Learn more about USM pages in the documentation'), 'https://docs.depaul.nl/usm/admin-panel/pages', ['target' => '_blank']) ?>.

</p>
<?php $this->endBlock(); ?>

<div class="content-toolbar">
    <?= Html::a(UsmModule::t('pages', 'Create new page'), ['create'], ['class' => 'btn btn-primary']); ?>
</div>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'options' => [
        'class' => 'table-responsive',
    ],
    'columns' => [
        [
            'attribute' => 'title',
            'format' => 'raw',
            'value' => function ($model) {
                return Html::a($model->title, ['interpret/page', 'id' => $model->id, 'returnUrl' => Url::current()], ['data-pjax' => 0]);
            }
        ],
        [
            'attribute' => 'access',
            'format' => 'raw',
            'value' => 'accessBadge',
            'filter' => Usm::getAccessOptions(),
        ],
        [
            'header' => 'In menu',
            'format' => 'raw',
            'value' => function ($data) {
                if ($data->menuItems == null) {
                    return Html::tag('small', Html::a(UsmModule::t('pages', "Make menu item&hellip;"), ["menu/create", "page" => $data->id, 'return' => Usm::returnUrl()], ['data-pjax' => 0]));
                } else {
                    $r = [];
                    foreach ($data->menuItems as $m) {
                        $r[] = Html::a("<span data-toggle='tooltip' data-placement='top' title='/{$m->redirect->url}'>" . $m->title . "</span>", ["menu/update", "id" => $m->id, 'return' => Usm::returnUrl()], ['data-pjax' => 0]);
                    }
                    return "<span class='badge rounded-pill text-bg-secondary'>" . count($data->menuItems) . "&times;</span> " . implode(", ", $r);
                }
            },
        ],
        [
            'header' => 'URLs',
            'format' => 'raw',
            'value' => function ($data) {
                if ($data->redirects == null) {
                    return Html::tag('i', UsmModule::t('usm', 'None'), ['class' => 'not-set']);
                } else {
                    $r = [];
                    foreach ($data->redirects as $m) {
                        $r[] = Html::a("<span>/" . $m->url . "</span>", ["redirects/update", "id" => $m->id, 'return' => Usm::returnUrl()], ['data-pjax' => 0]);
                    }
                    return "<span class='badge rounded-pill text-bg-secondary'>" . count($data->redirects) . "&times;</span> " . implode(", ", $r);
                }
            },
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'contentOptions' => [
                'class' => 'text-right',
                'style' => 'width:70px'
            ]
        ]
    ]
]);
?>

src/views/pages/update.php
<?php

use maerduq\usm\UsmModule;

$this->params['pageHeader'] = UsmModule::t('pages', "Edit page: {0}", [$model->title]);
$this->params['breadcrumbs'] = [
    ['label' => UsmModule::t('usm', 'Pages'), 'url' => ['index']],
    $model->title
];
?>

<?= $this->render('_form', ['model' => $model, 'returnUrl' => $returnUrl]) ?>