src/controllers/MenuController.php
<?php

namespace maerduq\usm\controllers;

use maerduq\usm\components\UsmController;
use maerduq\usm\components\Usm;
use maerduq\usm\models\MenuItem;
use maerduq\usm\models\Page;
use maerduq\usm\models\Redirect;
use maerduq\usm\UsmModule;
use Yii;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

class MenuController extends UsmController {

    public $options = [];

    public function behaviors() {
        $behaviors = parent::behaviors();
        $behaviors['verbs'] = [
            'class' => VerbFilter::class,
            'actions' => [
                'delete'  => ['post'],
                'ajax' => ['post']
            ],
        ];
        return $behaviors;
    }

    public function beforeAction($action) {
        if ($action->id === 'ajax') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionIndex($sudo = null) {
        $items = MenuItem::find()
            ->with(['redirect', 'page', 'children'])
            ->where(['parent_id' => null])
            ->orderBy(['position' => SORT_ASC])
            ->all();

        return $this->render('index', [
            'items' => $items,
            'sudo' => $sudo
        ]);
    }

    public function actionCreate($page = null, $return = null) {
        $model = new MenuItem();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', UsmModule::t('menu', 'Menu item has been created.'));
            return $this->redirect(Usm::returnUrl($return, ['update', 'id' => $model->id]));
        } elseif ($page != null) {
            $page = Page::findOne($page);
            if ($page !== null) {
                $model->visible = 1;
                $model->type = 'cms';
                $model->page_id = $page->id;
                $model->title = $page->title;
            }
        }

        $this->view->params['cms_options'] = $this->getOptions(Page::class, 'title', [], false);

        return $this->render('create', [
            'model' => $model,
            'return' => $return
        ]);
    }

    public function actionUpdate($id = null, $return = null) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', UsmModule::t('menu', 'Menu item has been edited.'));
            return $this->refresh();
        }

        $this->view->params['cms_options'] = $this->getOptions(Page::class, 'title', [], false);

        return $this->render('update', [
            'model' => $model,
            'return' => $return
        ]);
    }

    public function actionDelete($id = null) {
        $model = MenuItem::findOne($id);
        if ($model != null) {
            Redirect::deleteAll('menu_item_id = :id', ['id' => $id]);
            $model->delete();
            $sql = ($model->parent_id == null) ?
                "UPDATE " . MenuItem::tableName() . " SET position = position-1 WHERE parent_id IS NULL && position >= :order" :
                "UPDATE " . MenuItem::tableName() . " SET position = position-1 WHERE parent_id = :parent && position >= :order";
            $params = ($model->parent_id == null) ?
                ['order' => $model->position] :
                ['parent' => $model->parent_id, 'order' => $model->position];
            Yii::$app->db->createCommand($sql)->bindValues($params)->execute();
            Yii::$app->session->setFlash('success', UsmModule::t('menu', 'Menu item has been deleted.'));
        }
        $this->redirect(['index']);
        return;
    }


    public function actionAjax($action) {
        switch ($action) {
            case 'order':
                return $this->ajaxOrder();
                break;
            default:
                throw new NotFoundHttpException();
        }
    }

    public function ajaxOrder() {
        $newOrder = Yii::$app->request->post('newOrder');
        foreach ($newOrder as $op) {
            $item = MenuItem::findOne($op['id']);
            if ($item === null) {
                continue;
            }
            $item->parent_id = $op['parent_id'];
            $item->position = $op['position'];
            $item->save();
        }
        return 1;
    }

    /**
     * Finds the MenuItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MenuItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = MenuItem::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(UsmModule::t('error', 'The requested page does not exist.'));
    }
}

src/controllers/PagesController.php
<?php

namespace maerduq\usm\controllers;

use maerduq\usm\components\UsmController;
use maerduq\usm\components\Usm;
use maerduq\usm\models\Page;
use maerduq\usm\models\PageSearch;
use maerduq\usm\models\Translation;
use maerduq\usm\UsmModule;
use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;

class PagesController extends UsmController {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        $behaviors = parent::behaviors();
        $behaviors['verbs'] = [
            'class' => VerbFilter::class,
            'actions' => [
                'delete'  => ['post'],
            ],
        ];
        return $behaviors;
    }

    /**
     * Lists all Page models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new PageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate($return = null) {
        $model = new Page();
        $model->content = '<p>This is a new page!</p>';

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['interpret/page', 'id' => $model->id, 'usm' => ['editMode' => 1]]);
        }

        return $this->render('create', [
            'model' => $model,
            'return' => $return,
        ]);
    }

    public function actionView($id, $returnUrl = '/usm/pages/index') {
        return $this->redirect(['interpret/page', 'id' => $id, 'returnUrl' => $returnUrl]);
    }

    public function actionUpdate($id = null, $returnUrl = null) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            \Yii::$app->session->setFlash('success', UsmModule::t('pages', 'Page successfully saved'));
            return ($returnUrl === null) ? $this->refresh() : $this->redirect($returnUrl);
        }

        return $this->render('update', [
            'model' => $model,
            'returnUrl' => $returnUrl,
        ]);
    }

    public function actionDelete($id = null) {
        $model = Page::findOne($id);
        if ($model === null) {
            throw new HttpException(404, UsmModule::t('error', 'Page not found'));
        }

        $model->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Page model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Page the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Page::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(UsmModule::t('error', 'The requested page does not exist.'));
    }
}

src/views/menu/_form.php
<?php

use maerduq\usm\assets\pages\MenuFormAsset;
use yii\bootstrap5\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use maerduq\usm\components\Usm;
use maerduq\usm\UsmModule;

MenuFormAsset::register($this);

$form = ActiveForm::begin();
?>

<?= $form->field($model, 'visible')->checkbox([
    'template' => "<div class='checkbox-toggle-container'>\n{beginLabel}\n
        <div class=\"checkbox-toggle\">{input}<span class=\"slider round\"></span></div>\n
        {labelTitle}\n{endLabel}\n{error}\n{hint}\n</div>",
])->hint(UsmModule::t('menu', 'Whether this item should be shown in the menu')); ?>

<?php foreach (Usm::getLanguages() as $lang) : ?>
    <?php if ($lang === Usm::getBaseLanguage()) : ?>
        <?= $form->field($model, 'title', [
            'template' => (count(Usm::getLanguages()) === 1) ? "{label}\n{input}\n{hint}\n{error}" :
                "{label}\n<div class='input-group'>
                <span class='input-group-text'>{$lang}</span>
                {input}
                </div>\n{hint}\n{error}"
        ]) ?>
    <?php else : ?>
        <div class="mb-3">
            <div class="input-group">
                <span class="input-group-text"><?= $lang ?></span>
                <input type="text" class="form-control" name="MenuItem[translations][title][<?= $lang ?>]" value="<?= $model->getTranslation('title', $lang, false) ?>" />
            </div>
        </div>
    <?php endif ?>
<?php endforeach ?>

<?= $form->field($model, 'alias')->hint(UsmModule::t('menu', 'The alias for this menu item in the address bar. Should only contain lowercase characters and dashes. If this is left blank, an URL alias will be generated from the title.')); ?>

<hr />

<?= $form->field($model, 'type')->radioList($model->typeOptions)->hint(UsmModule::t('menu', 'What item should be linked to this menu item?')); ?>

<?= $form->field($model, 'page_id')->dropDownList($this->params['cms_options'], [
    'prompt' => '- ' . UsmModule::t('pages', 'Create new page'),
])->hint(($model->isNewRecord) ? '' : Html::a(UsmModule::t('pages', 'Edit page'), ['pages/update', 'id' => $model->page_id, 'returnUrl' => Url::current()])); ?>


<?= $form->field($model, 'pluginPage')->dropDownList($model->getPluginPageOptions(), ['prompt' => UsmModule::t('menu', 'Select a plugin page...')]) ?>

<?= $form->field($model, 'controllerId')->hint(UsmModule::t('menu', 'Do it like Yii routing does, i.e.: {0}', ['<code>/model/update?id=1</code>'])); ?>

<?= $form->field($model, 'url')->hint(UsmModule::t('menu', 'Just copy-paste your URL here, including the {0} part.', ['<code>https://</code>'])); ?>

<?= $form->field($model, 'access')->radioList(Usm::getAccessOptions(), ['size' => 3])->hint(UsmModule::t('menu', 'Which users should be able to see this menu item?')); ?>

<div class="btn-toolbar">
    <?= Html::submitButton((($model->isNewRecord) ? UsmModule::t('usm', 'Create') : UsmModule::t('usm', 'Update')), ['class' => 'btn btn-primary me-2']); ?>
    <?= Html::a(UsmModule::t('usm', 'Back'), Usm::returnUrl($return, ['index']), ['class' => 'btn btn-link']); ?>
</div>
<?php ActiveForm::end(); ?>

src/views/menu/_item.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use maerduq\usm\components\Usm;
use maerduq\usm\UsmModule;
use maerduq\usm\widgets\IconWidget;

?>
<div class="media <?php if ($model->visible != 1) : ?>bg-light<?php endif ?> d-flex align-items-center py-2 px-3">
    <div class="name flex-grow-1 fs-5">
        <?php
        if ($model->redirect !== null) {
            echo Html::tag('span', Html::a($model->title, ['/' . $model->redirect->url, 'returnUrl' => Url::current()]), ['data' => ['toggle' => "tooltip", 'placement' => "right"], 'title' => '/' . $model->redirect->url]);
            echo Html::tag('span', $model->title, ['class' => 'title-for-sorting', 'style' => 'display:none']);
        } else {
            echo Html::tag('span', $model->title);
        }
        ?>
    </div>
    <div class="actions">
        <?php if ($model->visible !== 1) : ?>
            <span class='badge rounded-pill text-bg-secondary lbl-visible'><?= UsmModule::t('menu', 'Hidden') ?></span>
        <?php endif ?>

        <?php
        $accessOptions = Usm::getAccessOptions();
        $accessColors = Usm::$accessColors;
        $access = $model->access;

        echo Html::tag('span', $accessOptions[$access], ['class' => 'badge rounded-pill lbl-access text-bg-' . $accessColors[$access]]);

        switch ($model->type) {
            case 'empty':
                echo "<span class='badge rounded-pill text-bg-secondary'>" . UsmModule::t('usm', 'Empty menu item') . "</span>";
                break;
            case 'cms':
                echo Html::a('<span class="badge rounded-pill text-bg-success" data-toggle="tooltip" data-placement="top" title="' . $model->page->title . '">' . UsmModule::t('usm', 'USM page') . '</span>', ['interpret/page', 'id' => $model->page->id, 'usm' => ['editMode' => 1], 'returnUrl' => Url::current()]);
                break;
            case 'plugin':
                echo '<span class="badge rounded-pill text-bg-danger" data-toggle="tooltip" data-placement="top" title="' . UsmModule::getInstance()->reverseLookupPluginPage($model->url) . '">' . UsmModule::t('usm', 'Plugin page') . '</span>';
                break;
            case 'php':
                echo '<span class="badge rounded-pill text-bg-warning" data-toggle="tooltip" data-placement="top" title="' . $model->url . '">' . UsmModule::t('usm', 'Yii controller') . '</span>';
                break;
            case 'link':
                echo Html::a('<span class="badge rounded-pill text-bg-info" data-toggle="tooltip" data-placement="top" title="' . $model->url . '">' . UsmModule::t('usm', 'Link') . '</span>', $model->url, ['target' => '_blank']);
                break;
        }
        ?>
    </div>
    <div class="buttons ms-2">
        <?php if ($model->redirect !== null) : ?>
            <?= Html::a(IconWidget::widget(['icon' => 'eye']), ['/' . $model->redirect->url, 'returnUrl' => Url::current()]) ?>
        <?php endif; ?>
        <?= Html::a(IconWidget::widget(['icon' => 'pencil']), ['update', 'id' => $model->id]) ?>
        <?= Html::a(IconWidget::widget(['icon' => 'trash']), ['delete', 'id' => $model->id], ['data' => ['method' => 'POST', 'confirm' => UsmModule::t('menu', 'Are you sure to delete this menu item?')]]) ?>
    </div>
</div>

src/views/menu/create.php
<?php

use maerduq\usm\UsmModule;

$this->title = UsmModule::t('menu', 'Create new menu item');
$this->params['breadcrumbs'] = [
    ['label' => UsmModule::t('usm', 'Menu'), 'url' => ['index']],
    $this->title,
];

?>

<?= $this->render('_form', ['model' => $model, 'return' => $return]) ?>

src/views/menu/index.php
<?php

use maerduq\usm\assets\pages\MenuOverviewAsset;
use maerduq\usm\components\Usm;
use maerduq\usm\UsmModule;
use yii\helpers\Html;
use yii\helpers\Url;

$this->params['pageHeader'] = UsmModule::t('usm', 'Menu');

$this->registerJsVar('ajaxUrl', Url::to(['ajax']));
$this->registerJsVar('accessOptions', Usm::getAccessOptions());
MenuOverviewAsset::register($this);

?>
<?php $this->beginBlock('intro'); ?>
<p>
    <?= UsmModule::t('menu', 'On this page you can edit the menu of your website.') ?>
    <?= Html::a(UsmModule::t('menu', 'Learn more about editing the menu in the documentation'), 'https://docs.depaul.nl/usm/admin-panel/menu', ['target' => '_blank']) ?>.

</p>
<?php $this->endBlock(); ?>

<section id="menu-overview-page">

    <div class="content-toolbar">
        <?= Html::a(UsmModule::t('menu', 'Create new menu item'), ['create'], ['class' => 'btn btn-primary me-2', 'id' => 'create-button']); ?>
        <label id="sort-mode-control">
            <div class="checkbox-toggle">
                <input type="checkbox" id="sort-mode-toggle">
                <span class="slider round"></span>
            </div>
            <?= UsmModule::t('menu', 'Order mode for menu items') ?>
        </label>
    </div>
    <?php if (count($items) == 0) : ?>
        <p><i><?= UsmModule::t('menu', 'You don\'t have a menu yet.') ?></i></p>
    <?php endif; ?>

    <ul class="item-list list-unstyled root">
        <?php foreach ($items as $item) : ?>
            <li data-id="<?= $item->id ?>">
                <?= $this->render('_item', ['model' => $item]) ?>
                <?php /* The following line should stay in one line to eliminate rendering whitespace within the item-list, while we use css :empty to highlight this element when ordering mode is active */ ?>
                <ul class="item-list list-unstyled"><?php foreach ($item->getChildren()->with(['redirect', 'page'])->orderBy(['position' => SORT_ASC])->each() as $subItem) : ?><?= Html::tag('li', $this->render('_item', ['model' => $subItem]), ['data-id' => $subItem->id]) ?><?php endforeach ?></ul>
            </li>
        <?php endforeach ?>
    </ul>
</section>

src/views/menu/update.php
<?php

use maerduq\usm\UsmModule;

$this->title = UsmModule::t('menu', "Edit menu item: {0}", [$model->title]);
$this->params['breadcrumbs'] = [
    ['label' => UsmModule::t('usm', 'Menu'), 'url' => ['index']],
    $this->title,
];

?>

<?= $this->render('_form', ['model' => $model, 'return' => $return]);